name: python

on: push

jobs:
  test_env:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Test env vars for python
      run: python -c 'import os;print(os.environ)'
      env:
        USERNAME: ${{ app_secrets.USERNAME }}
        PASSWORD: ${{ app_secrets.PASSWORD }}
    
    - name: Test inline env vars for python
      run: USERNAME=${{ secrets.USERNAME }} PASSWORD=${{ secrets.USERNAME }} python -c 'import os;print(os.environ)'
